"""add local_image_url to post

Revision ID: 8f3543a8d013
Revises: a7ae8fef011e
Create Date: 2026-04-05 14:01:38.120622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f3543a8d013'
down_revision = 'a7ae8fef011e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_image_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('local_image_url')

    # ### end Alembic commands ###
